wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
sequence_length:
  desc: null
  value: 256
print_interval:
  desc: null
  value: 10
validation_interval:
  desc: null
  value: 10
model_params:
  desc: null
  value:
    k: 256
    heads: 4
    depth: 3
    seq_length: 256
    num_tokens: 256
    num_classes: 256
optimizer_params:
  desc: null
  value:
    lr: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718054840
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.17.1
      8:
      - 5
      13: darwin-x86_64
